name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build application (Ignore ESLint errors)
        env:
          CI: false
          ESLINT_NO_DEV_ERRORS: true
        run: npm run build

      - name: Setup .ebextensions
        run: |
          # Create the .ebextensions directory
          mkdir -p .ebextensions
          
          # Create the staticfiles.config file with the required content
          cat > .ebextensions/staticfiles.config << 'EOL'
          option_settings:
            aws:elasticbeanstalk:container:nodejs: 
              NodeCommand: ""
            aws:elasticbeanstalk:container:nodejs:staticfiles:
              /: /
          EOL
          
          # Verify the file was created correctly
          ls -la .ebextensions/
          cat .ebextensions/staticfiles.config

      - name: Create deployment deployment package
        run: |
          cp -r .ebextensions build/
          cd build 
          zip -r ../epockalv-deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: epockalv
          environment_name: epockalv-prod
          version_label: ${{ github.sha }}
          region: ca-central-1
          deployment_package: epockalv-deploy.zip 